export const lang = {
  app: {
    name: 'BĐS Trong Tầm Tay',
    description: 'Tìm kiếm và chia sẻ bất động sản',
  },

  propertyTypes: {
    villa: 'Villa',
    biet_thu: 'Biệt thự',
    can_ho_dich_vu: 'Căn hộ dịch vụ',
  } as Record<string, string>,

  propertyStatuses: {
    active: 'Đang bán/cho thuê',
    sold: 'Đã bán',
    rented: 'Đã cho thuê',
  } as Record<string, string>,

  home: {
    heroTitle: 'Tìm danh mục bất động sản',
    heroSubtitle: 'Villa · Biệt thự · Căn hộ dịch vụ',
    resultsFiltered: 'Kết quả tìm kiếm:',
    resultsAll: 'Tất cả BĐS:',
    countUnit: 'căn',
    noResults: 'Không tìm thấy BĐS phù hợp',
    noResultsHint: 'Thử thay đổi bộ lọc',
  },

  search: {
    queryPlaceholder: 'Tìm theo ID (BDS-00001) hoặc tên...',
    cityLabel: 'Thành phố',
    cityAll: 'Tất cả thành phố',
    districtLabel: 'Quận/Huyện',
    districtAll: 'Tất cả quận/huyện',
    typeLabel: 'Loại BĐS',
    typeAll: 'Tất cả',
    typeAllLong: 'Tất cả loại',
    dateLabel: 'Thời gian',
    dateAll: 'Tất cả',
    date7: '7 ngày qua',
    date30: '30 ngày qua',
    date90: '3 tháng qua',
    date180: '6 tháng qua',
    filterBtn: 'Lọc',
  },

  property: {
    bedroomShort: 'PN',
    bedroomFull: 'phòng ngủ',
    descriptionTitle: 'Mô tả',
    postedDate: 'Ngày đăng',
    noImage: 'No img',
    notFound: 'Không tìm thấy BĐS',
  },

  admin: {
    brand: 'BĐS Manager',
    navList: 'Danh sách BĐS',
    navAdd: 'Thêm BĐS mới',
    navProfile: 'Hồ sơ',
    logout: 'Đăng xuất',
    pageTitle: 'Danh sách BĐS',
    addBtn: 'Thêm mới',
    propertyCount: (n: number) => `${n} bất động sản`,
    table: {
      colImage: 'Ảnh',
      colId: 'ID',
      colName: 'Tên BĐS',
      colType: 'Loại',
      colArea: 'Khu vực',
      colPrice: 'Giá',
      colStatus: 'Trạng thái',
      colActions: 'Thao tác',
      empty: 'Không có BĐS nào.',
      deleteConfirm: (id: string) => `Xóa BĐS ${id}? Hành động này không thể hoàn tác.`,
      deleteSuccess: (id: string) => `Đã xóa ${id}`,
      deleteError: 'Xóa thất bại:',
    },
  },

  form: {
    sectionBasic: 'Thông tin cơ bản',
    nameLabel: 'Tên BĐS',
    namePlaceholder: 'VD: Villa Hồ Tây 3 phòng ngủ',
    typeLabel: 'Loại BĐS',
    cityLabel: 'Thành phố',
    districtLabel: 'Quận/Huyện',
    addressLabel: 'Địa chỉ cụ thể',
    addressPlaceholder: 'VD: 12 Nguyễn Huệ',
    priceLabel: 'Giá (VNĐ)',
    pricePlaceholder: 'VD: 5000000000',
    areaSqmLabel: 'Diện tích (m²)',
    areaSqmPlaceholder: 'VD: 200',
    bedroomsLabel: 'Số phòng ngủ',
    bedroomsPlaceholder: 'VD: 3',
    statusLabel: 'Trạng thái',
    descLabel: 'Mô tả',
    descPlaceholder: 'Mô tả chi tiết về bất động sản...',
    sectionImages: 'Ảnh BĐS',
    imageCount: (n: number) => `${n} ảnh`,
    compressingBtn: 'Đang nén...',
    addImageBtn: 'Thêm ảnh',
    uploadClickHint: 'Nhấp để chọn ảnh',
    uploadMultiHint: 'Hỗ trợ nhiều ảnh cùng lúc',
    uploadingMsg: 'Đang tải lên...',
    newBadge: 'Mới',
    cancelBtn: 'Hủy',
    saveBtn: 'Lưu thay đổi',
    createBtn: 'Thêm BĐS',
    errorRequired: 'Vui lòng điền đầy đủ thông tin bắt buộc',
    errorCompress: 'Nén ảnh thất bại, thử lại',
    errorUpload: 'Upload thất bại',
    errorPrefix: 'Lỗi:',
    successCreate: 'Đã thêm BĐS mới',
    successUpdate: 'Đã cập nhật BĐS',
  },

  profile: {
    pageTitle: 'Hồ sơ cá nhân',
    sectionTitle: 'Thông tin hiển thị với khách',
    avatarLabel: 'Ảnh đại diện',
    changeAvatar: 'Đổi ảnh',
    nameLabel: 'Tên hiển thị',
    namePlaceholder: 'VD: Nguyễn Văn A',
    phoneLabel: 'Số điện thoại',
    phonePlaceholder: 'VD: 0901234567',
    bioLabel: 'Giới thiệu',
    bioPlaceholder: 'Vài dòng giới thiệu về bạn, kinh nghiệm, khu vực chuyên...',
    saveBtn: 'Lưu hồ sơ',
    success: 'Đã lưu hồ sơ',
    errorPrefix: 'Lưu thất bại:',
    errorName: 'Vui lòng nhập tên hiển thị',
    agentTitle: 'Người đăng tin',
    callBtn: 'Gọi điện',
    zaloBtn: 'Nhắn Zalo',
  },

  download: {
    btn: (n: number) => `Lưu (${n})`,
    loading: 'Đang tải...',
    preparing: (n: number) => `Đang chuẩn bị ${n} ảnh...`,
    success: 'Tải xuống thành công!',
    errorEmpty: 'Không có ảnh để tải',
    errorFail: 'Tải thất bại, vui lòng thử lại',
  },

  share: {
    btn: 'Chia sẻ',
    copied: 'Đã sao chép',
    successToast: 'Đã sao chép link!',
    zaloBtn: 'Zalo',
    zaloToast: 'Đã sao chép link! Mở Zalo và dán vào chat.',
  },

  login: {
    title: 'Quản trị BĐS',
    subtitle: 'Đăng nhập để tiếp tục',
    emailLabel: 'Email',
    passwordLabel: 'Mật khẩu',
    submitBtn: 'Đăng nhập',
    errorInvalid: 'Email hoặc mật khẩu không đúng',
  },
}
